#!/usr/bin/env python3
"""Emit paper/sections/x_cis.tex ; the appendix confidence-interval reference table.

The body of the paper shows point estimates only (readability); this table restores the
full 95% bootstrap CIs for the headline quantities, generated directly from ci_numbers.json
so the appendix can never drift from the source of truth. Wrapped in \\showcitrue by its
appendix host so the \\ci macro renders here even though it is hidden everywhere else.
"""
import json, os

HERE = os.path.dirname(__file__)
CI = json.load(open(os.path.join(HERE, "..", "..", "paper", "ci_numbers.json")))

def fmt(v, pct=False, dec=3):
    if v is None: return "--"
    return f"{v*100:.1f}" if pct else f"{v:.{dec}f}"

def row(label, key, field, pct=False, dec=3):
    d = CI.get(key, {}).get(field)
    if not d: return None
    p, lo, hi = d["point"], d.get("lo"), d.get("hi")
    n = d.get("n_prompts", "")
    ci = f"[{fmt(lo,pct,dec)},\\,{fmt(hi,pct,dec)}]" if lo is not None else "--"
    return f"{label} & {fmt(p,pct,dec)} & {ci} & {n} \\\\"

# (section header, [(label, key, field, pct, dec), ...])
BLOCKS = [
    ("Ranking preservation (gate grid, $\\tauc{=}0.10$)", [
        ("Median $\\rhosp$", "gate_tau=0.10", "median_rho", False, 3),
        ("Mean $\\rhosp$", "gate_tau=0.10", "mean_rho", False, 3),
        ("Top-1 agreement", "gate_tau=0.10", "top1", True, 3),
    ]),
    ("Ranking preservation (official 946-prompt VBench)", [
        ("Median $\\rhosp$", "vbench", "median_rho", False, 3),
        ("Mean $\\rhosp$", "vbench", "mean_rho", False, 3),
        ("Top-1 agreement", "vbench", "top1", True, 3),
    ]),
    ("Selection value at $N{=}8$ (reward units)", [
        ("Gain, best-of-8 full", "main_N=8", "gain_bon", False, 3),
        ("Gain, \\cachedsearch{}-keep", "main_N=8", "gain_keep", False, 3),
        ("Gain, \\cachedsearch{}-commit", "main_N=8", "gain_commit", False, 3),
    ]),
    ("Commit capture vs.\\ search width (\\%)", [
        ("$N{=}2$", "width_N=2", "capture_commit", True, 3),
        ("$N{=}4$", "width_N=4", "capture_commit", True, 3),
        ("$N{=}8$", "width_N=8", "capture_commit", True, 3),
        ("$N{=}16$", "width_N=16", "capture_commit", True, 3),
    ]),
]

lines = [
    "% AUTO-GENERATED by code/paper_figs/make_ci_table.py from ci_numbers.json. Do not hand-edit.",
    "\\begin{table}[t]\\centering\\small",
    "\\caption{\\textbf{Full 95\\% bootstrap confidence intervals} for the headline quantities "
    "(the body reports the point estimates only, per \\S\\ref{sec:exp-setup}). "
    "Intervals are percentile bootstrap over prompts ($B{=}10^4$); $n$ is the prompt count. "
    "Regenerated directly from \\texttt{ci\\_numbers.json}.}",
    "\\label{tab:cis}",
    "\\begin{tabular}{lccc}",
    "\\toprule",
    "Quantity & Point & 95\\% CI & $n$ \\\\",
]
for title, rows in BLOCKS:
    lines.append("\\midrule")
    lines.append(f"\\multicolumn{{4}}{{l}}{{\\textit{{{title}}}}} \\\\")
    for r in rows:
        out = row(*r)
        if out: lines.append(out)
lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

dest = os.path.join(HERE, "..", "..", "paper", "sections", "x_cis.tex")
open(dest, "w").write("\n".join(lines) + "\n")
print("wrote", dest, "-", sum(len(b[1]) for b in BLOCKS), "rows")
